fix(CI): add tag existence verification in release and pre-release workflows

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -46,8 +46,15 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           pre_release_branches: "fast"
 
-      - name: Fetch tags
-        run: git fetch --tags
+      - name: Verify tag exists
+        run: |
+          git fetch --tags
+          if git rev-parse "${{ steps.tag_version.outputs.new_tag }}" >/dev/null 2>&1; then
+            echo "Tag exists"
+          else
+            echo "Tag missing!"
+            exit 1
+          fi
 
       - name: Clone `CSharp-Workflow-Scripts` Python script
         run: git clone https://github.com/T2PeNBiX99wcoxKv3A4g/CSharp-Workflow-Scripts.git .scripts
